[book]
authors = ["Cem Akarsubaşı"]
language = "en"
multilingual = false
src = "src"
title = "02562 Rendering Journal"

[output.html]
mathjax-support = true

[preprocessor.bib]
bibliography = "bibliography.bib"